workflows:
  ios-workflow:
    name: iOS Build (No Codesign)
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Flutter clean
        script: flutter clean
      
      - name: Install dependencies
        script: flutter pub get
      
      - name: Update iOS deployment target
        script: |
          cd ios
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' Runner.xcodeproj/project.pbxproj
      
      - name: Pod install
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
      
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
    
    artifacts:
      - build/ios/iphoneos/*.app
      - flutter_drive.log