// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeSrazaEWP23IdeeOoHyTR1sg3NtM2cnE',
    appId: '1:809695848626:web:380e14d125bb579dc1c1ab',
    messagingSenderId: '809695848626',
    projectId: 'meca-learning-app-771e8',
    authDomain: 'meca-learning-app-771e8.firebaseapp.com',
    storageBucket: 'meca-learning-app-771e8.firebasestorage.app',
    measurementId: 'G-KJCGPGDKHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzeMuwGLAYJ9aiIAuuZvnpVmS9iKpuzhA',
    appId: '1:809695848626:android:ea9288986614d48ac1c1ab',
    messagingSenderId: '809695848626',
    projectId: 'meca-learning-app-771e8',
    storageBucket: 'meca-learning-app-771e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWif2tv_EECLOIY0AZX6ecbB3faesZDGc',
    appId: '1:809695848626:ios:a22d2ccd42b82e6ec1c1ab',
    messagingSenderId: '809695848626',
    projectId: 'meca-learning-app-771e8',
    storageBucket: 'meca-learning-app-771e8.firebasestorage.app',
    iosBundleId: 'com.example.mecaLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWif2tv_EECLOIY0AZX6ecbB3faesZDGc',
    appId: '1:809695848626:ios:a22d2ccd42b82e6ec1c1ab',
    messagingSenderId: '809695848626',
    projectId: 'meca-learning-app-771e8',
    storageBucket: 'meca-learning-app-771e8.firebasestorage.app',
    iosBundleId: 'com.example.mecaLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeSrazaEWP23IdeeOoHyTR1sg3NtM2cnE',
    appId: '1:809695848626:web:4bcddbb4ceb20c78c1c1ab',
    messagingSenderId: '809695848626',
    projectId: 'meca-learning-app-771e8',
    authDomain: 'meca-learning-app-771e8.firebaseapp.com',
    storageBucket: 'meca-learning-app-771e8.firebasestorage.app',
    measurementId: 'G-TMLXK55H5J',
  );
}
